### ISSUE TITLE
优化返利页面提现细节问题

### ISSUE THREAD

**Issue by Miaogn** [BobCoderS9/SSPanel-Metron#10]
返利提现输入负值，显示提现成功，虽然不影响，但是后台提现处理有记录，同时建议每次提现最大值自定义，输入负值提现显示非法请求.

**Comment by BobCoderS9** [comment]
已修复

**Comment by Miaogn** [comment]
谢谢大佬修复，好像还是有个小bug，用户页面显示提现问题解决，后台提现处理依旧会有提现记录，即使显示提现金额大于0元，数据还是会写入payback_take_log表中
