### ISSUE TITLE
试用套餐可以多次购买

### ISSUE THREAD

**Issue by v5oo** [BobCoderS9/SSPanel-Metron#100]
![QQ浏览器截图20220925224236](https://user-images.githubusercontent.com/77771685/192150094-3ca3db3e-0bbf-4f58-a705-4a3c72b32da5.jpg)
![QQ浏览器截图20220925223851](https://user-images.githubusercontent.com/77771685/192150096-eee1f2bc-b6fa-42fa-abef-5e9ea496d823.jpg)
在购买记录里，这为兄弟不知道为什么可以多次购买试用套餐，总共成功购买试用套餐6次，共300G，用户中心里显示的流量也是300G，应该是购买一次后，试用计划就看不到了，怎么还能连着买呢

**Comment by evolutionboy** [comment]
你把试用套餐也弄个会员等级几就好了，
因为只有会员等级等于多少，才能显示 试用套餐样
默认的好像是-1， 且从未使用过。
难道你这个用户，从未使用，且-1级？否则 他看都看不到吧。
这是个正常人吗，一分钟买 一次。

**Comment by BobCoderS9** [comment]
自己检查商品等级是否没有配置
