### ISSUE TITLE
修改节点密码方面存在问题

### ISSUE THREAD

**Issue by Miaogn** [BobCoderS9/SSPanel-Metron#11]
通过订阅设置自定义修改节点连接密码，不会变动v2ray用户的uuid, 只有重置订阅链接，才能让之前的uuid失效，并生成新的uuid，更新节点连接uuid.

**Comment by BobCoderS9** [comment]
你要先搞明白节点链接密码是什么再来提问。

**Comment by NMSLSE** [comment]
个人觉得楼主提的没毛病，本身v2ray的uuid就相当于SSR的节点连接密码；
修改节点连接密码时重置v2ray的uuid合情合理，重置订阅链接时重置uuid反而不大合理；

建议加入 **修改节点连接密码时重置v2ray的uuid** ，并且将**重置订阅链接时重置uuid**改成**仅重置订阅链接**；

希望大佬 @BobCoderS9 可以采纳一下我的建议
