### ISSUE TITLE
Issue with web api

### ISSUE THREAD

**Issue by theMeysam** [BobCoderS9/SSPanel-Metron#110]
Hi dear friends;

When I try to use Web API I have below issues:
1- I try to use login via rest api, with email and passwd to get set-cookie.
2- when I try to get users (for example), I set below object to header:
{"Cookie": "key=123456789..."}

I expected, the second item, return my users as a json, while it return html of website!!!

Can anyone help me, what is my problem?
Best regards;

**Comment by alvisnparker** [comment]
Hi, 
I am also facing same problem of Api on my website of [Ez-park](https://theparkingarea.com/ez-park/). If you get solution of this mention me here.
Thanks.
