### ISSUE TITLE
套餐商店下套餐描述全部都是被划线的

### ISSUE THREAD

**Issue by Wang-KH** [BobCoderS9/SSPanel-Metron#114]
不管怎么设置都是被划线
<img width="307" alt="image" src="https://user-images.githubusercontent.com/12857702/221632576-dedba2c9-99f7-42b5-bd22-8139a6275309.png">
<img width="434" alt="image" src="https://user-images.githubusercontent.com/12857702/221632687-7f08a687-b7fb-4f92-8b92-f1995b8fc459.png">

**Comment by NMSLOOO** [comment]
改成true就好了，建议close
