### ISSUE TITLE
composer的weget命令已经不可以了吗？

### ISSUE THREAD

**Issue by AD696** [BobCoderS9/SSPanel-Metron#123]
wget https://getcomposer.org/installer -O composer.phar && php composer.phar && php composer.phar install
我使用这个包搭建的时候发现weget了依赖但是进行下一步没有这些文件，项目下载的也很快，依赖包少了很多，建议更新一下

**Comment by BobCoderS9** [comment]
你这个只是换了个composer的下载地址，跟依赖包没关系
