### ISSUE TITLE
登录界面无法用回车键登录

### ISSUE THREAD

**Issue by hfqwaini** [BobCoderS9/SSPanel-Metron#127]
如题，望增加

**Comment by hfqwaini** [comment]
> 如题，望增加

**Comment by q42602736** [comment]
> > 如题，望增加

有在这里问的时间还不如去问AI，AI都帮你写好了，修改resources/views/metron/auth/login.tpl 文件添加如下代码：
<script>
document.addEventListener("keypress", function(event) {
  if (event.key === "Enter") {
    document.getElementById("login_submit").click();
  }
});
</script>
