### ISSUE TITLE
客服系统前端不显示

### ISSUE THREAD

**Issue by atomiky** [BobCoderS9/SSPanel-Metron#13]
#客服系统设置，注册地址 https://www.mylivechat.com
$_ENV['enable_mylivechat'] = true;   //是否开启客服系统
$_ENV['mylivechat_id'] = '63453672';      //客服系统ID

**Comment by BobCoderS9** [comment]
@atomiky metron并没有支持这个客服系统，只有Crisp和Chatra，等我有空再添加吧

**Comment by NMSLSE** [comment]
这个在安安可维护的上游已经弃用了，没必要再添加吧

**Comment by atomiky** [comment]
config里面只有mylivechat的配置啊（crisp已被替换为mylivechat），views里面也只有mylivechat.tpl
Crisp该怎么配置呢

**Comment by BobCoderS9** [comment]
@atomiky 面板使用问题请去群里面咨询
