### ISSUE TITLE
能否将vless vmess订阅合并在一起

### ISSUE THREAD

**Issue by worldneedme** [BobCoderS9/SSPanel-Metron#137]
1，小火箭一键订阅也能同时支持vless和vmess
2，适配clash meta
3，跟随新版ssp-uim，将reality和tuic协议也加入进去，扩展订阅下发
4，扩展一下sing-box内核支持的协议，例如hysteria

**Comment by a8866051** [comment]
@worldneedme 合并很简单价格case就行了代码直接复制粘贴

**Comment by a8866051** [comment]
@worldneedme 合并很简单加个case就行了代码直接复制粘贴

**Comment by a8866051** [comment]
@a8866051 reality支持代码在这里https://github.com/Anankke/SSPanel-Uim/pull/2137

**Comment by jameqq** [comment]
借楼问下怎么把vmess和trojan拆分  订阅只留下vmess和vless  然后订阅获取的列表排序是根据名字，而不是根据节点类型排序
