### ISSUE TITLE
后台返利页面提现记录问题

### ISSUE THREAD

**Issue by Miaogn** [BobCoderS9/SSPanel-Metron#14]
用户页面显示提现问题解决，后台提现处理依旧会有提现记录，即使显示提现金额大于0元，数据还是会写入payback_take_log表中

**Comment by BobCoderS9** [comment]
@Miaogn 根本没懂你想描述什么东西，提现当然会有提现记录

**Comment by Miaogn** [comment]
用户邀请界面输入负值数值，显示提现金额需大于0元，后台提现处理也会记录提现记录，无用记录.
