### ISSUE TITLE
希望可以将当前的节点配置改成和uim一样的custom_config

### ISSUE THREAD

**Issue by xiaoyaohanyue** [BobCoderS9/SSPanel-Metron#141]
<img width="337" alt="image" src="https://github.com/BobCoderS9/SSPanel-Metron/assets/44468010/a7083a3a-c5c2-465b-a0a5-b813cd1f2135">

**Comment by lajichang0** [comment]
XrayR对接ss时有一样的问题，只能监听后面端口
