### ISSUE TITLE
用户天数无法重置

### ISSUE THREAD

**Issue by wuchen4588** [BobCoderS9/SSPanel-Metron#144]
![image](https://github.com/BobCoderS9/SSPanel-Metron/assets/60568101/fbedbfe0-d35a-4683-9d69-a234a9901109)
![image](https://github.com/BobCoderS9/SSPanel-Metron/assets/60568101/2f8e93f1-acd1-45db-a8fb-8910b5433fff)

**Comment by BobCoderS9** [comment]
自己检查CheckUserClassExpire定时任务。
