### ISSUE TITLE
添加商品 服务支持的 Material-icon 的问题

### ISSUE THREAD

**Issue by YamyuCheung** [BobCoderS9/SSPanel-Metron#156]
check-全球节点分布;check-快速客服响应;check-全平台客户端
却看到这些字全部都被划掉了
<img width="176" alt="image" src="https://github.com/BobCoderS9/SSPanel-Metron/assets/36185093/732df3af-cbef-4093-8c4f-609e36e8f9a2">

**Comment by q42602736** [comment]
check改成true试试
