### ISSUE TITLE
请问如何设置对接TG机器人

### ISSUE THREAD

**Issue by q42602736** [BobCoderS9/SSPanel-Metron#168]
按照网上SSPanel-UIM的教程运行php xcat setTelegram  发现弹错Unable to load class: \App\Command\setTelegram，BOB的这个sspanel无法对接TG机器人吗？

**Comment by BobCoderS9** [comment]
所以你为什么拿uim的教程来配置metron的机器人。

**Comment by q42602736** [comment]
因为没找到教程，看了下，使用 php xcat Tool setTelegram  能成功了，但是还是没法用了，我再找找教程

**Comment by q42602736** [comment]
> 所以你为什么拿uim的教程来配置metron的机器人。

因为没找到教程，看了下，使用 php xcat Tool setTelegram  能成功了，但是还是没法用，联系机器人没反应，我再找找教程
