### ISSUE TITLE
[BUG】添加购买套餐赠送流量+时间的营销功能

### ISSUE THREAD

**Issue by leisuvpn** [BobCoderS9/SSPanel-Metron#172]
此功能仅在使用在线支付的情况下有用，使用余额支付不生效
我已经替换了相关文件，发现赠送的流量和时长都会直接覆盖掉原有的套餐剩余时间和剩余流量
我测试购买365天的年付套餐，每月300G流量，设置赠送7天和100G流量，购买成功后时间却只有7天和100G，每月把套餐原有的叠加

**Comment by BobCoderS9** [comment]
已修复。
