### ISSUE TITLE
定时任务成功执行，面板等级、流量到期不重置

### ISSUE THREAD

**Issue by 3434737407** [BobCoderS9/SSPanel-Metron#19]
查看定时任务日志tail /var/log/cron有执行记录
Oct 31 19:19:01 VM-4-6-centos CROND[17679]: (root) CMD (php /www/wwwroot/文件夹/xcat Job UserJob)
Oct 31 19:19:01 VM-4-6-centos CROND[17680]: (root) CMD (php /www/wwwroot/w文件夹/xcat Job CheckUserExpire)
Oct 31 19:19:01 VM-4-6-centos CROND[17681]: (root) CMD (php /www/wwwroot/文件夹/xcat Job CheckUserClassExpire)

**Comment by BobCoderS9** [comment]
@3434737407 你这是执行记录，你的报错信息呢？这怎么看？
