### ISSUE TITLE
节点分组逻辑好像有问题

### ISSUE THREAD

**Issue by 61743** [BobCoderS9/SSPanel-Metron#21]
现有:
  A节点 分组1等级1
  B节点 分组2等级2
预期:
  购买了B组节点的用户看不到A组节点
实际发生: 
  购买了B组节点的用户依旧能看到A组节点

**Comment by BobCoderS9** [comment]
这个逻辑是用户能看到小于和等于当前等级的节点，所以等级2的用户能看到等级1的节点
