### ISSUE TITLE
等级过期未降级

### ISSUE THREAD

**Issue by atomiky** [BobCoderS9/SSPanel-Metron#27]
会员账户到期后，等级不变，会员时长为-3天

**Comment by NMSLSE** [comment]
定时任务问题吧，这也提issues😅

**Comment by atomiky** [comment]
0 0 * * * php -n /var/www/sspanel/xcat Job DailyJob
*/1 * * * * php /var/www/sspanel/xcat Job CheckJob
*/1 * * * * php /var/www/sspanel/xcat Job CheckUserClassExpire
*/1 * * * * php /var/www/sspanel/xcat Job CheckUserExpire
定时任务已经开启了

**Comment by NMSLSE** [comment]
执行下看有没有什么错误

**Comment by atomiky** [comment]
php /var/www/sspanel/xcat Job CheckUserExpire
方法不存在.

请问这个是什么问题啊

**Comment by BobCoderS9** [comment]
代码不是最新版
