### ISSUE TITLE
订阅

### ISSUE THREAD

**Issue by ymlsn** [BobCoderS9/SSPanel-Metron#29]
![图片](https://user-images.githubusercontent.com/69228575/146667374-eaf5cc2c-50bf-4e89-a027-a78bc10d3061.png)
这啥问题，以前的mt主题没问题，复制订阅地址到浏览器也下载不了，出现500错误
![图片](https://user-images.githubusercontent.com/69228575/146667397-677cb5dd-82d0-48d4-b101-07bd8f3fee15.png)

**Comment by BobCoderS9** [comment]
报错信息都没，看什么

**Comment by ymlsn** [comment]
![图片](https://user-images.githubusercontent.com/69228575/146667677-4bfacee8-efa5-4432-8ede-b78bd610671a.png)

**Comment by ymlsn** [comment]
![图片](https://user-images.githubusercontent.com/69228575/146667693-20e67ff8-3bd5-4b83-be1e-0d33458c3421.png)

**Comment by BobCoderS9** [comment]
@ymlsn debug打开看报错信息

**Comment by ymlsn** [comment]
![图片](https://user-images.githubusercontent.com/69228575/146667984-e5be4864-598a-45f4-9ac2-3c5f0bf77499.png)

**Comment by ymlsn** [comment]
Illuminate\Database\QueryException thrown with message "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node_sort' in 'order clause' (SQL: select * from `ss_node` where `sort` in (0, 10, 11, 12, 13, 14, 15) and `type` = 1 order by `node_sort` desc, `name` asc)"

Stacktrace:
#28 Illuminate\Database\QueryException in /www/wwwroot/www.sspanel.cc/vendor/illuminate/database/Connection.php:729
#27 PDOException in /www/wwwroot/www.sspanel.cc/vendor/illuminate/database/Connection.php:333
#26 PDO:prepare in /www/wwwroot/www.sspanel.cc/vendor/illuminate/database/Connection.php:333
#25 Illuminate\Database\Connection:Illuminate\Database\{closure} in /www/wwwroot/www.sspanel.cc/vendor/illuminate/database/Connection.php:722
#24 Illuminate\Database\Connection:runQueryCallback in /www/wwwroot/www.sspanel.cc/vendor/illuminate/database/Connection.php:685
#23 Illuminate\Database\Connection:run in /www/wwwroot/www.sspanel.cc/vendor/illuminate/database/Connection.php:349
#22 Illuminate\Database\Connection:select in /www/wwwroot/www.sspanel.cc/vendor/illuminate/database/Query/Builder.php:1610
#21 Illuminate\Database\Query\Builder:runSelect in /www/wwwroot/www.sspanel.cc/vendor/illuminate/database/Query/Builder.php:1596
#20 Illuminate\Database\Query\Builder:get in /www/wwwroot/www.sspanel.cc/vendor/illuminate/database/Eloquent/Builder.php:625
#19 Illuminate\Database\Eloquent\Builder:getModels in /www/wwwroot/www.sspanel.cc/vendor/illuminate/database/Eloquent/Builder.php:316
#18 Illuminate\Database\Eloquent\Builder:get in /www/wwwroot/www.sspanel.cc/src/Utils/URL.php:194
#17 App\Utils\URL:getNodes in /www/wwwroot/www.sspanel.cc/src/Utils/URL.php:259
#16 App\Utils\URL:getNew_AllItems in /www/wwwroot/www.sspanel.cc/src/Controllers/LinkController.php:849
#15 App\Controllers\LinkController:getClash in /www/wwwroot/www.sspanel.cc/src/Controllers/LinkController.php:171
#14 App\Controllers\LinkController:GetContent in /www/wwwroot/www.sspanel.cc/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:40
#13 call_user_func in /www/wwwroot/www.sspanel.cc/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:40
#12 Slim\Handlers\Strategies\RequestResponse:__invoke in /www/wwwroot/www.sspanel.cc/vendor/slim/slim/Slim/Route.php:281
#11 Slim\Route:__invoke in /www/wwwroot/www.sspanel.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:117
#10 Slim\Route:callMiddlewareStack in /www/wwwroot/www.sspanel.cc/vendor/slim/slim/Slim/Route.php:268
#9 Slim\Route:run in /www/wwwroot/www.sspanel.cc/vendor/slim/slim/Slim/App.php:503
#8 Slim\App:__invoke in /www/wwwroot/www.sspanel.cc/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php:70
#7 Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware:__invoke in /www/wwwroot/www.sspanel.cc/vendor/slim/slim/Slim/DeferredCallable.php:57
#6 call_user_func_array in /www/wwwroot/www.sspanel.cc/vendor/slim/slim/Slim/DeferredCallable.php:57
#5 Slim\DeferredCallable:__invoke in /www/wwwroot/www.sspanel.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#4 call_user_func in /www/wwwroot/www.sspanel.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#3 Slim\App:Slim\{closure} in /www/wwwroot/www.sspanel.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:117
#2 Slim\App:callMiddlewareStack in /www/wwwroot/www.sspanel.cc/vendor/slim/slim/Slim/App.php:392
#1 Slim\App:process in /www/wwwroot/www.sspanel.cc/vendor/slim/slim/Slim/App.php:297
#0 Slim\App:run in /www/wwwroot/www.sspanel.cc/public/index.php:45

**Comment by BobCoderS9** [comment]
@ymlsn 数据库少字段，明显从老版本升级的时候没有导入新的sql

**Comment by ymlsn** [comment]
奇怪了，3个数据库我都导入了demo_help.sql，demo_help_class.sql，glzjin_all.sql

**Comment by ymlsn** [comment]
手动改了下字段，已经ok了

**Comment by visense** [comment]
> 手动改了下字段，已经ok了

同样的问题，需要改哪个字段？

**Comment by dmdmdmxy** [comment]
> 手动改了下字段，已经ok了

请问是如何添加解决的
