### ISSUE TITLE
公告邮件不发送

### ISSUE THREAD

**Issue by xiaoyaohanyue** [BobCoderS9/SSPanel-Metron#36]
公告里面发送邮件显示发送成功，实际上并没有 发送邮件，tgbot成功在群里通知了公告内容，在找回密码以及注册邮箱验证码均可正常使用邮箱，只有公告处使用邮箱没反应

**Comment by BobCoderS9** [comment]
@xiaoyaohanyue 检查邮件队列日志是否报错，建议更新master分支代码，上次优化了邮件队列发送

**Comment by xiaoyaohanyue** [comment]
在哪个地方看邮件队列日志呀，我就是昨晚刚刚从最新master分支搭建的

**Comment by a8866051** [comment]
查看数据库里面的email_queue是否仍有邮件未发出。

**Comment by xiaoyaohanyue** [comment]
email_queue为空
