### ISSUE TITLE
是否支持ShadowsocksAEAD？

### ISSUE THREAD

**Issue by visense** [BobCoderS9/SSPanel-Metron#40]
大佬，这个面板是否支持ShadowsocksAEAD？

**Comment by NMSLSE** [comment]
https://github.com/BobCoderS9/SSPanel-Metron/commit/0431a3810560a2399ddf4bac7a8a8712a8e7f817

**Comment by visense** [comment]
> [0431a38](https://github.com/BobCoderS9/SSPanel-Metron/commit/0431a3810560a2399ddf4bac7a8a8712a8e7f817)

感谢大佬回复，但是好像不支持aes-128-gcm, aes-256-gcm, chacha20-ietf-poly1305？如果支持要怎么操作呢？

**Comment by visense** [comment]
> [0431a38](https://github.com/BobCoderS9/SSPanel-Metron/commit/0431a3810560a2399ddf4bac7a8a8712a8e7f817)

搞好了，谢谢大佬！！！

**Comment by keevu8x86hn** [comment]
> > [0431a38](https://github.com/BobCoderS9/SSPanel-Metron/commit/0431a3810560a2399ddf4bac7a8a8712a8e7f817)
> 
> 搞好了，谢谢大佬！！！

可以教我吗 ! 我搞不聊 =‘=
