### ISSUE TITLE
重置密码时邮件提示，邮件发送失败请联系网站管理员，但是能正常收到邮件，

### ISSUE THREAD

**Issue by xinan1212** [BobCoderS9/SSPanel-Metron#41]

**Comment by yangyzp** [comment]
更新后，问题依然存在，提示有错误，邮件其实已经发送

**Comment by BobCoderS9** [comment]
测试没有任何问题，自己检查代码书否更新成功。
![image](https://user-images.githubusercontent.com/70191444/148479521-4078632c-5a0d-48fe-9ab1-eefcb9f41a95.png)
![image](https://user-images.githubusercontent.com/70191444/148479539-7845cbd5-e1cd-4a31-8e3d-d92b339b8dc3.png)

**Comment by yangyzp** [comment]
用其他发信方式没问题，用阿里云发信会报错。
今天看到已经修复了。返现维护
