### ISSUE TITLE
旧版升级后订阅出错

### ISSUE THREAD

**Issue by ouyangss** [BobCoderS9/SSPanel-Metron#42]
从旧版metron进行git pull升级最新版本后，订阅出不来了，debug后显示如下：
<img width="1979" alt="debug" src="https://user-images.githubusercontent.com/33536260/148469897-a64f8763-1b20-4383-bdba-93e46c69cbef.png">
听说是改一个字段就可以，请问大佬们，改哪个字段？

**Comment by BobCoderS9** [comment]
这种问题你提issues干嘛，不知道去群里面问吗
