### ISSUE TITLE
对接Shadowsocks - V2Ray-Plugin

### ISSUE THREAD

**Issue by visense** [BobCoderS9/SSPanel-Metron#43]
按照https://crackair.gitbook.io/xrayr-project/dui-jie-sspanel/sspanel/dui-jie-shadowsocks-v2rayplugin
的教程对接Shadowsocks - V2Ray-Plugin连接失败，请问面板能否支持Shadowsocks - V2Ray-Plugin

**Comment by BobCoderS9** [comment]
不懂Shadowsocks，建议咨询其他人。

**Comment by visense** [comment]
> 不懂Shadowsocks，建议咨询其他人。

感谢大佬回复！
