### ISSUE TITLE
求增加新功能

### ISSUE THREAD

**Issue by xiaoyaohanyue** [BobCoderS9/SSPanel-Metron#49]
像这个一样：
https://github.com/Anankke/SSPanel-Uim/issues/1403

**Comment by BobCoderS9** [comment]
@xiaoyaohanyue 没看懂这是什么功能呢，有啥用

**Comment by a8866051** [comment]
@GibHubTang 付费定制120u起步

**Comment by JusufUs** [comment]
好功能 其实用处也不大 自己标记节点也是不错的 一般客户(小白居多)不会去网站里看这些

**Comment by BobCoderS9** [comment]
已添加。
