### ISSUE TITLE
用户注册受限

### ISSUE THREAD

**Issue by ErikLensherrRR** [BobCoderS9/SSPanel-Metron#54]
用户注册 最大用户数受限于端口数65535个
sspanel已解除限制 请查看

**Comment by yangyzp** [comment]
膜拜大佬。居然还有这个问题，从来没有考虑过·~~~
不过这确实也是个bug。

**Comment by hentaipzl** [comment]
https://github.com/Anankke/SSPanel-Uim/commit/9887451cf8b244f6eae33053f6d00adf58888170#diff-896f11bbdecb08eacf7d0a385a5881c2e9135a913ee1ec8279d6396ca24b6dd7

**Comment by BobCoderS9** [comment]
已修复
