### ISSUE TITLE
管理面板中系统概览里的节点在线情况显示问题

### ISSUE THREAD

**Issue by chiyamahisayoshi** [BobCoderS9/SSPanel-Metron#58]
描述
实际显示可用的线路是14个。节点在线情况中显示数量为10。
14个线路中Trojan线路为4个，怀疑是Trojan的线路在节点在线情况中不显示。（XrayR后端）

**Comment by 531700266qq** [comment]
手机那里是汇总是黑的

**Comment by 531700266qq** [comment]
怎么解决啊

**Comment by NMSLSE** [comment]
@531700266qq 为什么这种问题也来issues下问？

**Comment by 531700266qq** [comment]
问你一个比较难搞的问题  支付对接不跳转我搭建的支付网站  V2Board可以啊

**Comment by NMSLSE** [comment]
不懂、不会、不知道，付费50U的话可以帮你解决

**Comment by 531700266qq** [comment]
可以

**Comment by NMSLSE** [comment]
TG发一下吧

**Comment by 531700266qq** [comment]
加你吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BobCoderS9/SSPanel-Metron"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月3日(星期四) 晚上9:24
***@***.***&gt;;
抄送:&nbsp;"(4I16R18) ***@***.******@***.***&gt;;
主题:&nbsp;Re: [BobCoderS9/SSPanel-Metron] 管理面板中系统概览里的节点在线情况显示问题 (Issue #58)





 
TG发一下吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NMSLSE** [comment]
我加你TG就行了

**Comment by BobCoderS9** [comment]
这个非面板问题，自己检查
