### ISSUE TITLE
ss 密码单端口的方式不可用

### ISSUE THREAD

**Issue by csdfsdffese** [BobCoderS9/SSPanel-Metron#6]
ss单端口设置后，节点密码一直显示为承载用户的密码，并非自己的密码

**Comment by BobCoderS9** [comment]
不会ss，建议找其他人付费解决吧

**Comment by NMSLSE** [comment]
SS添加单端口参考：
https://github.com/Anankke/SSPanel-Uim/commit/232c87c0ff80d0118249d9c0eb161f869e7f4c5d
个人已经测试成功

**Comment by arxuan18** [comment]
> SS添加单端口参考： [Anankke/SSPanel-Uim@232c87c](https://github.com/Anankke/SSPanel-Uim/commit/232c87c0ff80d0118249d9c0eb161f869e7f4c5d) 个人已经测试成功

太感谢你了老哥，终于解决了
