### ISSUE TITLE
增加一个去掉注册昵称吧

### ISSUE THREAD

**Issue by JusufUs** [BobCoderS9/SSPanel-Metron#60]
注册时候填写越少客户觉得越好，可以让name默认使用email，JS文件加密了我自行改了下没改成

**Comment by BobCoderS9** [comment]
我记得配置里面有控制昵称显示的，自己去查看下

**Comment by JusufUs** [comment]
> 我记得配置里面有控制昵称显示的，自己去查看下

大佬，真没有找到，我又认真的看了一遍
