### ISSUE TITLE
似乎无法使用smtp发送邮件

### ISSUE THREAD

**Issue by RealSlakey** [BobCoderS9/SSPanel-Metron#68]
尝试了outlook、gmail、yandex还有网易，执行邮件队列、每日用户详情等任务后均不能发送出邮箱，点击获取验证码提示 发送错误 0

**Comment by RealSlakey** [comment]
看数据库似乎是未能成功加入到email_queue

**Comment by BobCoderS9** [comment]
这个是你自己问题
