### ISSUE TITLE
删除用户显示“ [object Object] 发生了错误”

### ISSUE THREAD

**Issue by lishoul1979** [BobCoderS9/SSPanel-Metron#7]
删除用户显示
![image](https://user-images.githubusercontent.com/63201654/132628767-ec009ab3-6648-497c-95ae-120cfaf5a4d0.png)

控制台显示

![image](https://user-images.githubusercontent.com/63201654/132628957-0dda2708-7c46-43a9-aea0-4f8d257eb0f8.png)

**Comment by lishoul1979** [comment]
https://github.com/Anankke/SSPanel-Uim/issues/1222

uim也有此类问题

**Comment by BobCoderS9** [comment]
![image](https://user-images.githubusercontent.com/70191444/133231587-eafca327-2c55-4457-a54e-77f50510ce64.png)
没有问题，请检查你自己的配置
