### ISSUE TITLE
注册点击验证码按钮没有反馈，用户误以为没有点到，会重复点击按钮，导致一下发出多封邮件

### ISSUE THREAD

**Issue by gagdsd** [BobCoderS9/SSPanel-Metron#71]
注册点击验证码按钮没有反馈，用户误以为没有点到，会重复点击按钮，导致一下发出多封邮件

**Comment by NMSLSE** [comment]
附议

**Comment by suxiyun** [comment]
可不可以添加 验证码发送中的提示 待成功后 再提示发送成功

**Comment by JusufUs** [comment]
附议+1

**Comment by BobCoderS9** [comment]
已经改好，测试下吧。

**Comment by gagdsd** [comment]
你好，刚刚测试了，并没有解决。点击反馈很慢。连点几次还是发出多封邮件，并且后面再换邮箱注册的直接不工作了，收不到邮件了。

**Comment by gagdsd** [comment]
你好，刚刚测试了，并没有解决这个问题，按钮反馈还是慢。连点几次，还是发出了多封邮件，然后后面再换邮箱的注册测试，直接收不到邮件了。
