### ISSUE TITLE
cdn.jsdelivr资源被墙了

### ISSUE THREAD

**Issue by tristesky** [BobCoderS9/SSPanel-Metron#76]
cdn.jsdelivr.net 资源被墙了打不开首页

**Comment by waloyn** [comment]
用户端的可以下载资源到本地，修改.metron_setting.php的$_MT['assets_true'] = false;配置，管理端的在哪改呢？
另外把cdn改成fastly，部分地区也是可以的。

**Comment by tristesky** [comment]
> 用户端的可以下载资源到本地，修改.metron_setting.php的$_MT['assets_true'] = false;配置，管理端的在哪改呢？ 另外把cdn改成fastly，部分地区也是可以的。

谢谢，用户端的我改了，管理端的目前不知道哪里改。

**Comment by BobCoderS9** [comment]
后台管理面板的自己去下载和替换，这个懒得搞，并不影响使用
