### ISSUE TITLE
订阅更新

### ISSUE THREAD

**Issue by hotket** [BobCoderS9/SSPanel-Metron#77]
发现V2Board的clash订阅导入默认24小时更新，要是sspanel订阅也默认导入支持24小时自动更新就好了

**Comment by BobCoderS9** [comment]
添加了。

**Comment by keevu8x86hn** [comment]
spanel订阅也默认导入支持24小时自动更新！我可以在哪个目录更新这个？ 因为我目前使用的是 v1.2.2 版本 31.03.2022。 或者我需要做什么来更新您的最新修改，而不影响正在运行的系统

**Comment by chengleiicn579** [comment]
spanel订阅也默认导入支持24小时自动更新！我可以在哪个目录更新这个？ 因为我目前使用的是 v1.2.2 版本 31.03.2022。 或者我需要做什么来更新您的最新修改，而不影响正在运行的系统

> 添加了。
