### ISSUE TITLE
更新后tgbot重复发信问题

### ISSUE THREAD

**Issue by KANIKIG** [BobCoderS9/SSPanel-Metron#8]
commit 直接更新后出现bot重复发信问题，会将发给用户的最后一条信息每一分钟重复发送一次。
将 `src/Utils/Telegram/Process.php` **32** 行
`($Message->getReplyToMessage()->getText() != null)`
改回
`($Message->getReplyToMessage() != null)`
问题解决，bot按钮与命令均正常工作。

**Comment by BobCoderS9** [comment]
已修复
