### ISSUE TITLE
关于共享账号的问题，是否能够为共享账号添加一个群组的标记

### ISSUE THREAD

**Issue by SHctt** [BobCoderS9/SSPanel-Metron#88]
部分共享账号，例如netflix，一般一个账号只有5个位置，建议可以使用群组来定义属于哪个群组的几个人可以使用某一组账号，群组的规则其实可以不使用大于某个数字，而是等于指定的群组就显示相应的共享账号就可以了

**Comment by BobCoderS9** [comment]
这种需求建议你自己找人定制吧，大部分都用不到这么详细的功能
