### ISSUE TITLE
请问SS有端口偏移功能吗

### ISSUE THREAD

**Issue by PAKingdom** [BobCoderS9/SSPanel-Metron#91]
我尝试了 sspanel=uim 的[写法](https://github.com/whunt1/SSPanel_Uim_port_offset)
xrayr 的[写法](https://xrayr-project.github.io/XrayR-doc/dui-jie-sspanel/sspanel/shadowsocks.html)

(他并不起作用

**Comment by NMSLSE** [comment]
前端本身就支持的，并不需要改动代码，但是后端需要自己设置偏移

**Comment by PAKingdom** [comment]
我只需要在前端配置偏移，请问格式是？我尝试了两种写法

**Comment by NMSLSE** [comment]
IP或域名;port=监听端口#连接端口

**Comment by PAKingdom** [comment]
吧节点编辑页面改成 0 不让他下发配置文件就可以了 
域名或IP;port=监听端口#连接端口;server=xx  生效
