### ISSUE TITLE
易支付的支付宝回调成功，但是页面一直在加载处理中，无法完成支付返回结果////// V免签也不能正常回调成功。

### ISSUE THREAD

**Issue by XiaoLangCat** [BobCoderS9/SSPanel-Metron#94]
用最新的代码的搭建的，对接的易支付，支付宝支付成功，我的支付后台也是支付完成回调成功的。
sspanel-metron 面板 支付宝完成支付后一直在处理中，显示这个     正在处理，请稍等 
尝试过多台不同系统的服务器搭建，均是这样。

**Comment by XiaoLangCat** [comment]
可以在我搭建好的面板验证，[metron.fanqiangvpnnet.xyz](http://metron.fanqiangvpnnet.xyz/)
测试账户： test@test.com   密码： test

**Comment by XiaoLangCat** [comment]
且微信支付无法对接，显示   epay 支付系统错误,请联系客服
请明示如何修改，谢谢。

**Comment by XiaoLangCat** [comment]
v免签对接的支付宝和微信，均不能正常完成回调。
v免签后台订单显示 通知失败，重新补单也显示失败，异步通知返回错误，查看通知返回数据是failed

**Comment by XiaoLangCat** [comment]
我还没有设置宝塔面板的计划任务配置，应该和这个没有关系吧。

**Comment by BobCoderS9** [comment]
易支付微信已经修复了，至于v免签版本太多，你得根据你的v免签版本来自己修改代码适配。
