### ISSUE TITLE
您好，面板现在不支持对接Shadowsocks - V2Ray-Plugin吗？

### ISSUE THREAD

**Issue by XiaoLangCat** [BobCoderS9/SSPanel-Metron#96]
添加的Shadowsocks - V2Ray-Plugin 类型节点，用户端节点信息一直提示：您的加密方式非 AEAD 系列，无法使用此节点.
请问现在是不能对接Shadowsocks - V2Ray-Plugin   节点吗？我用的XrayR 后端对接。

而且我已经添加了单端口多用户的用户，该承载用户的自定义加密是 aes-128-gcm ，已经是AEAD加密方式了。
也添加了该用户的承载端口。

**Comment by BobCoderS9** [comment]
这个没玩过，不过看了代码应该是没问题的，检查你配置的net是不是配置的obfs
