### ISSUE TITLE
metron的bug之套餐流量提前重置出错

### ISSUE THREAD

**Issue by MRright2** [BobCoderS9/SSPanel-Metron#97]
如果用户购买多个套餐（带有自动重置的），会导致提前重置错误。

**Comment by BobCoderS9** [comment]
@MRright2 自己把流量重置模式改为metron，然后运行php xcat MetronTask changebought 将用户最后一个套餐设置为有效套餐 (仅需执行一次)

**Comment by MRright2** [comment]
感谢bob大佬，问题已经解决，确实是流量重置模式问题。
