### ISSUE TITLE
shadowsocks节点加密方式不支持aes-256-gcm等aead算法吗？

### ISSUE THREAD

**Issue by zhuxindong** [BobCoderS9/SSPanel-Metron#99]
shadowsocks节点加密方式不支持aes-256-gcm等aead算法吗？
![image](https://user-images.githubusercontent.com/24989246/191668111-a3680bb4-6fd4-4252-8e16-d43057126f2d.png)

**Comment by BobCoderS9** [comment]
上传了，测试下
